include("ex0_apolar.jl")
include("ex1_symmetric.jl")	
include("ex2_multilinear.jl")	
include("ex3_multiprony.jl")	
include("ex4_moments.jl")	
include("ex5_decompose.jl")
#include("ex6_perproots.jl")
#include("ex7_newton.jl")
#include("ex7.1_RNS.jl")

